name: Code Check
on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 🛠️ Build Next.js App
    runs-on: ubuntu-latest
    steps:
      - name: 🛠️ Build
        run: pnpm run build
  lint:
    name: ⬣ ESLint, ʦ TypeScript, and 💅 Prettier
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: 🤌 Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'pnpm'

      - name: 📥 Download deps
        run: pnpm install --no-frozen-lockfile

      - name: 🔬 Lint
        run: pnpm run lint:strict

      - name: 🔎 Type check
        run: pnpm run typecheck

      - name: 💅 Prettier check
        run: pnpm run format:check
